default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: wechat_starter_development
  adapter: sqlite3
  host: localhost
test:
  <<: *default
  database: wechat_starter_test

production:
  <<: *default
  database: wechat_starter_production
